general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: 'DBS Japan Shared_eu10'
      space: 'demo-eu10'
      credentialsId: 'CF_CREDENTIALSID'
